### ISSUE TITLE
How to fix "OSError: [Errno 2] No such file or directory" 

### ISSUE THREAD

**Issue by shuiyouwen** [zjn0505/adb-alfred#9]
[16:19:20.520] adb[Debug] 01'c667fe25', {
  aapt_path = "/Volumes/Disk/Android/sdk/build-tools/29.0.2/aapt"
  adb_path = "/Volumes/Disk/Android/sdk/platform-tools/adb"
  apksigner_path = "/Volumes/Disk/Android/sdk/build-tools/29.0.2"
  config_clipboard = "1"
  device_api = "28"
  emulator_path = "/Volumes/Disk/Android/sdk/emulator"
  full_info = "Xiaomi - Mi 6 - Android 9, API 28"
  his_tag = "c667fe25"
  ip = "10.200.192.123/24"
  name = "Mi 6"
  serial = "c667fe25"
  status = "device"
}
[16:19:20.522] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.523] adb[Filter] Processing complete
[16:19:20.524] adb[Filter] Passing output 'c667fe25' to Arg and Vars
[16:19:20.525] adb[Arg and Vars] Processing complete
[16:19:20.526] adb[Arg and Vars] Passing output '' to Filter
[16:19:20.527] adb[Filter] Processing complete
[16:19:20.528] adb[Filter] Passing output '' to Filter
[16:19:20.529] adb[Filter] Processing complete
[16:19:20.530] adb[Filter] Passing output '' to Script Filter
[16:19:20.541] adb[Filter] Passing output '' to Debug
[16:19:20.542] adb[Debug] 02'', {
  aapt_path = "/Volumes/Disk/Android/sdk/build-tools/29.0.2/aapt"
  adb_path = "/Volumes/Disk/Android/sdk/platform-tools/adb"
  apksigner_path = "/Volumes/Disk/Android/sdk/build-tools/29.0.2"
  config_clipboard = "1"
  device_api = "28"
  emulator_path = "/Volumes/Disk/Android/sdk/emulator"
  full_info = "Xiaomi - Mi 6 - Android 9, API 28"
  his_tag = "c667fe25"
  ip = "10.200.192.123/24"
  name = "Mi 6"
  serial = "c667fe25"
  status = "device"
}
[16:19:20.544] adb[Arg and Vars] Passing output '' to Filter
[16:19:20.544] adb[Arg and Vars] Passing output '' to Filter
[16:19:20.545] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.546] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.547] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.548] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.549] adb[Script Filter] Passing output 'c667fe25' to Filter
[16:19:20.550] adb[Script Filter] Queuing argument ''
[16:19:20.682] adb[Script Filter] Script with argv '(null)' finished
[16:19:20.715] ERROR: adb[Script Filter] Code 1: Traceback (most recent call last):
  File "scripts/show_device_options.py", line 12, in <module>
    rc = subprocess.call(['/usr/local/bin/scrcpy', '-v'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zjn0505** [comment]
Thanks for filing this bug. Please check [v1.10.2](https://github.com/zjn0505/adb-alfred/releases/tag/v1.10.2) release.

**Comment by shuiyouwen** [comment]
可以了，非常棒！
